import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Bug Analysis App",
  description: "Generated by v0",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* BUG #6: Missing viewport meta tag for proper mobile scaling */}
        <meta name="viewport" content="width=device-width" />
      </head>
      <body>
        {children}
      </body>
    </html>
  )
}
